name: StairSeat
api: 3.14.1
main: korado531m7\StairSeat\StairSeat
version: 1.5.10
author: korado531m7
description: Enable to sit on the stair block
mcpe-protocol: 471
permissions:
  stairseat.toggle:
    description: "Toggle to sit"
    default: true
